using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Base class for obstacles generated by levelgenerator.
/// *NOTE: This was mainly designed to be use with the non implemented pooling system.
/// </summary>
public class Obstacle : MonoBehaviour
{

    private float m_RotationSpeed = 1;

    //Randomize the obstacle
    private void OnEnable()
    {
        m_RotationSpeed *= Random.Range(0.5f, 1.5f);
        transform.localScale *= Random.Range(0.5f, 1.2f);
    }

    //Rotate the obstacle
    void Update()
    {
        transform.RotateAroundLocal(Vector3.up, m_RotationSpeed * Time.deltaTime);
    }

}
